### ISSUE TITLE
The repository does not contain a CC metadata file

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/cc-licenses#39]
## Description
Each repo in the CC organisation should have a `.cc-metadata.yml` file. This one does not.

## Expectation
The `.cc-metadata.yml` file should be present.

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by snehal199** [comment]
Can I work on this one too @dhruvkb ?

**Comment by dhruvkb** [comment]
@snehal199 yeah, sure. Go ahead.
